// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MailComm.proto

package com.example.bachelor;

/**
 * <pre>
 * The response contains the unecrypted byte stream of an mime mail.
 * its a byte stream because its still encrypted with signal.
 * </pre>
 *
 * Protobuf type {@code bachelor.DecryptResponse}
 */
public  final class DecryptResponse extends
    com.google.protobuf.GeneratedMessageLite<
        DecryptResponse, DecryptResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:bachelor.DecryptResponse)
    DecryptResponseOrBuilder {
  private DecryptResponse() {
    unencryptedMail_ = com.google.protobuf.ByteString.EMPTY;
  }
  public static final int UNENCRYPTED_MAIL_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString unencryptedMail_;
  /**
   * <code>bytes unencrypted_mail = 1;</code>
   * @return The unencryptedMail.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getUnencryptedMail() {
    return unencryptedMail_;
  }
  /**
   * <code>bytes unencrypted_mail = 1;</code>
   * @param value The unencryptedMail to set.
   */
  private void setUnencryptedMail(com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    unencryptedMail_ = value;
  }
  /**
   * <code>bytes unencrypted_mail = 1;</code>
   */
  private void clearUnencryptedMail() {
    
    unencryptedMail_ = getDefaultInstance().getUnencryptedMail();
  }

  public static com.example.bachelor.DecryptResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.bachelor.DecryptResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.bachelor.DecryptResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.bachelor.DecryptResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.bachelor.DecryptResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.bachelor.DecryptResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.bachelor.DecryptResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.bachelor.DecryptResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.bachelor.DecryptResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.example.bachelor.DecryptResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.bachelor.DecryptResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.bachelor.DecryptResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.example.bachelor.DecryptResponse prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * The response contains the unecrypted byte stream of an mime mail.
   * its a byte stream because its still encrypted with signal.
   * </pre>
   *
   * Protobuf type {@code bachelor.DecryptResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.example.bachelor.DecryptResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:bachelor.DecryptResponse)
      com.example.bachelor.DecryptResponseOrBuilder {
    // Construct using com.example.bachelor.DecryptResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>bytes unencrypted_mail = 1;</code>
     * @return The unencryptedMail.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getUnencryptedMail() {
      return instance.getUnencryptedMail();
    }
    /**
     * <code>bytes unencrypted_mail = 1;</code>
     * @param value The unencryptedMail to set.
     * @return This builder for chaining.
     */
    public Builder setUnencryptedMail(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUnencryptedMail(value);
      return this;
    }
    /**
     * <code>bytes unencrypted_mail = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUnencryptedMail() {
      copyOnWrite();
      instance.clearUnencryptedMail();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:bachelor.DecryptResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.example.bachelor.DecryptResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "unencryptedMail_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\n";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.example.bachelor.DecryptResponse> parser = PARSER;
        if (parser == null) {
          synchronized (com.example.bachelor.DecryptResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.example.bachelor.DecryptResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:bachelor.DecryptResponse)
  private static final com.example.bachelor.DecryptResponse DEFAULT_INSTANCE;
  static {
    DecryptResponse defaultInstance = new DecryptResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      DecryptResponse.class, defaultInstance);
  }

  public static com.example.bachelor.DecryptResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<DecryptResponse> PARSER;

  public static com.google.protobuf.Parser<DecryptResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

