// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MailComm.proto

package com.example.bachelor;

public interface DecryptRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bachelor.DecryptRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>bytes encrypted_mail = 1;</code>
   * @return The encryptedMail.
   */
  com.google.protobuf.ByteString getEncryptedMail();
}
