// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MailComm.proto

package com.example.bachelor;

public interface DecryptResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bachelor.DecryptResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>bytes unencrypted_mail = 1;</code>
   * @return The unencryptedMail.
   */
  com.google.protobuf.ByteString getUnencryptedMail();
}
