// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MailComm.proto

package com.example.bachelor;

/**
 * <pre>
 * The request message containing the user's name.
 * </pre>
 *
 * Protobuf type {@code bachelor.DecryptRequest}
 */
public  final class DecryptRequest extends
    com.google.protobuf.GeneratedMessageLite<
        DecryptRequest, DecryptRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:bachelor.DecryptRequest)
    DecryptRequestOrBuilder {
  private DecryptRequest() {
    encryptedMail_ = com.google.protobuf.ByteString.EMPTY;
  }
  public static final int ENCRYPTED_MAIL_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString encryptedMail_;
  /**
   * <code>bytes encrypted_mail = 1;</code>
   * @return The encryptedMail.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getEncryptedMail() {
    return encryptedMail_;
  }
  /**
   * <code>bytes encrypted_mail = 1;</code>
   * @param value The encryptedMail to set.
   */
  private void setEncryptedMail(com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    encryptedMail_ = value;
  }
  /**
   * <code>bytes encrypted_mail = 1;</code>
   */
  private void clearEncryptedMail() {
    
    encryptedMail_ = getDefaultInstance().getEncryptedMail();
  }

  public static com.example.bachelor.DecryptRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.bachelor.DecryptRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.bachelor.DecryptRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.bachelor.DecryptRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.bachelor.DecryptRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.bachelor.DecryptRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.bachelor.DecryptRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.bachelor.DecryptRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.bachelor.DecryptRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.example.bachelor.DecryptRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.bachelor.DecryptRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.bachelor.DecryptRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.example.bachelor.DecryptRequest prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * The request message containing the user's name.
   * </pre>
   *
   * Protobuf type {@code bachelor.DecryptRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.example.bachelor.DecryptRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:bachelor.DecryptRequest)
      com.example.bachelor.DecryptRequestOrBuilder {
    // Construct using com.example.bachelor.DecryptRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>bytes encrypted_mail = 1;</code>
     * @return The encryptedMail.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getEncryptedMail() {
      return instance.getEncryptedMail();
    }
    /**
     * <code>bytes encrypted_mail = 1;</code>
     * @param value The encryptedMail to set.
     * @return This builder for chaining.
     */
    public Builder setEncryptedMail(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setEncryptedMail(value);
      return this;
    }
    /**
     * <code>bytes encrypted_mail = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEncryptedMail() {
      copyOnWrite();
      instance.clearEncryptedMail();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:bachelor.DecryptRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.example.bachelor.DecryptRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "encryptedMail_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\n";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.example.bachelor.DecryptRequest> parser = PARSER;
        if (parser == null) {
          synchronized (com.example.bachelor.DecryptRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.example.bachelor.DecryptRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:bachelor.DecryptRequest)
  private static final com.example.bachelor.DecryptRequest DEFAULT_INSTANCE;
  static {
    DecryptRequest defaultInstance = new DecryptRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      DecryptRequest.class, defaultInstance);
  }

  public static com.example.bachelor.DecryptRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<DecryptRequest> PARSER;

  public static com.google.protobuf.Parser<DecryptRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

