// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MailComm.proto

package com.example.bachelor;

public interface GreetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bachelor.Greet)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
